services:
  db:
    image: mysql:8.0
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: Vaishu_171105
      MYSQL_DATABASE: ecommerce
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pVaishu_171105"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: .
    container_name: ecommerce-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vaishu_171105
    ports:
      - "9090:9090"
    restart: unless-stopped
